
# --------------------------------------------------------------------------
# Everything above this line is generated by lib/mklab.nix from lab.nix.
# Everything below is plain bash so it can be shellchecked and read normally.
# --------------------------------------------------------------------------

export LIBVIRT_DEFAULT_URI="$URI"

KEYDIR="${XDG_CONFIG_HOME:-$HOME/.config}/lfcs-lab"
SSH_KEY="$KEYDIR/id_lab"
LETTERS=(b c d e f g)

log()  { printf '\033[36m::\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31mxx\033[0m %s\n' "$*" >&2; exit 1; }

dom() { printf '%s-%s' "$LAB" "$1"; }

known() {
  local n
  for n in "${NODES[@]}"; do
    if [ "$n" = "$1" ]; then return 0; fi
  done
  return 1
}

# No arguments means "the nodes marked autostart in lab.nix".
pick() {
  local n
  if [ "$#" -gt 0 ]; then
    for n in "$@"; do
      if ! known "$n"; then die "unknown node: $n"; fi
    done
    printf '%s\n' "$@"
  else
    printf '%s\n' "${AUTONODES[@]}"
  fi
}

state_of() {
  virsh domstate "$(dom "$1")" 2>/dev/null | head -n1 | tr -d '\r' || true
}

SSH_OPTS=(
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o LogLevel=ERROR
  -o ConnectTimeout=5
)

sshx() {
  local n="$1"; shift
  ssh -i "$SSH_KEY" "${SSH_OPTS[@]}" "$LABUSER@${NODE_IP[$n]}" "$@"
}

# The same call, but bounded. `timeout` runs a command, not a shell function,
# so the ssh invocation is spelled out again rather than wrapping sshx.
sshx_t() {
  local secs="$1" n="$2"; shift 2
  timeout "$secs" ssh -i "$SSH_KEY" "${SSH_OPTS[@]}" "$LABUSER@${NODE_IP[$n]}" "$@"
}

preflight() {
  if ! virsh -c "$URI" version >/dev/null 2>&1; then
    die "cannot reach $URI. Check that libvirtd is running and that you are in the libvirt group:
     sudo systemctl enable --now libvirtd
     sudo usermod -aG libvirt \"\$USER\" && newgrp libvirt"
  fi
  if [ ! -w /dev/kvm ]; then
    warn "/dev/kvm is not writable by you — guests will run under slow software emulation"
  fi
}

# install runs for twenty minutes and then needs root again at the very end,
# to copy the 'clean' snapshot — long after sudo's timestamp has expired. That
# prompts for a password into a terminal nobody is watching, times out, and
# kills the run one step from the finish line with every other step done.
# Refresh the timestamp for as long as the command lasts.
keep_sudo_alive() {
  sudo -v || die "install needs sudo: the guest disks live under $STATE"
  while true; do
    sudo -n true 2>/dev/null || break
    sleep 50
  done &
  SUDO_PID=$!
  trap 'kill "$SUDO_PID" 2>/dev/null || true' EXIT
}

ensure_key() {
  mkdir -p "$KEYDIR"
  if [ ! -f "$SSH_KEY" ]; then
    log "generating a lab-only ssh key at $SSH_KEY"
    ssh-keygen -t ed25519 -N "" -f "$SSH_KEY" -C "lfcs-lab" >/dev/null
  fi
}

fetch_images() {
  local key url file
  for key in "${!IMG_URL[@]}"; do
    url="${IMG_URL[$key]}"
    file="${IMG_FILE[$key]}"
    if sudo test -f "$STATE/base/$file"; then
      log "base image already present: $file"
    else
      log "downloading $key base image — this is the slow part, roughly 600 MB"
      curl -fL --progress-bar -o "/tmp/$file.part" "$url"
      sudo mv "/tmp/$file.part" "$STATE/base/$file"
    fi
  done
}

# qemu holds a write lock on a running guest's disk, so recreating one under a
# live domain fails with 'Failed to get "write" lock' — and would be a bad idea
# if it succeeded. Stop whatever is up before the disks are rebuilt. Only nodes
# that are actually running, so a genuine first install waits on nothing.
stop_running() {
  local n st running=()
  for n in "${NODES[@]}"; do
    st="$(state_of "$n")"
    if [ -n "$st" ] && [ "$st" != "shut off" ]; then running+=("$n"); fi
  done
  if [ "${#running[@]}" -gt 0 ]; then
    log "stopping ${running[*]} first — install rebuilds their disks"
    cmd_down "${running[@]}"
  fi
}

make_disks() {
  local n="$1" distro base root i
  distro="${NODE_DISTRO[$n]}"
  base="$STATE/base/${IMG_FILE[$distro]}"
  root="$STATE/disks/$n-root.qcow2"
  # Overlay on the shared base image: a few MB per node instead of a few GB.
  sudo qemu-img create -q -f qcow2 -F qcow2 -b "$base" "$root" "${NODE_ROOTGB[$n]}G"
  for ((i = 0; i < ${NODE_EXTRA[$n]}; i++)); do
    sudo qemu-img create -q -f qcow2 \
      "$STATE/disks/$n-vd${LETTERS[$i]}.qcow2" "${NODE_EXTRAGB[$n]}G"
  done
  log "$n: root ${NODE_ROOTGB[$n]}G + ${NODE_EXTRA[$n]} spare disks of ${NODE_EXTRAGB[$n]}G"
}

make_seed() {
  local n="$1" tmp pub
  pub="$(cat "$SSH_KEY.pub")"
  tmp="$(mktemp -d)"
  mkdir -p "$tmp/cidata"
  sed "s|@SSH_PUBKEY@|$pub|" "$MANIFEST/cloud-init/$n/user-data" > "$tmp/cidata/user-data"
  cp "$MANIFEST/cloud-init/$n/meta-data" "$tmp/cidata/meta-data"
  xorriso -as mkisofs -quiet -output "$tmp/seed.iso" \
    -volid CIDATA -joliet -rock "$tmp/cidata"
  sudo cp "$tmp/seed.iso" "$STATE/seed/$n-seed.iso"
  rm -rf "$tmp"
}

# The UUID in the manifest is derived from the object's name, so redefining is
# an update. Anything defined before that — by an older version of this repo,
# where libvirt assigned a random UUID — collides by name and has to go first.
uuid_in() { sed -n 's|.*<uuid>\(.*\)</uuid>.*|\1|p' "$1" | head -n1; }

define_nets() {
  local f name want have
  for f in "$MANIFEST"/networks/*.xml; do
    name="$(basename "$f" .xml)"
    want="$(uuid_in "$f")"
    have="$(virsh net-uuid "$name" 2>/dev/null | tr -d '\r' | head -n1)"

    if [ -n "$have" ] && [ "$have" != "$want" ]; then
      warn "$name predates stable UUIDs; recreating it once"
      # Only disruptive to guests attached right now, and install defines
      # networks before it starts anything.
      virsh net-destroy "$name" >/dev/null 2>&1 || true
      virsh net-undefine "$name" >/dev/null
    fi

    virsh net-define "$f" >/dev/null
    virsh net-autostart "$name" >/dev/null
    virsh net-start "$name" >/dev/null 2>&1 || true
    log "network $name defined"
  done
}

define_domains() {
  local n d want have
  for n in "${NODES[@]}"; do
    d="$(dom "$n")"
    want="$(uuid_in "$MANIFEST/domains/$n.xml")"
    have="$(virsh domuuid "$d" 2>/dev/null | tr -d '\r' | head -n1)"

    if [ -n "$have" ] && [ "$have" != "$want" ]; then
      # Undefining a running domain leaves it transient, which would quietly
      # lose the definition on shutdown. Say so rather than do that.
      if [ "$(state_of "$n")" = "running" ]; then
        warn "$d predates stable UUIDs and is running — shut it down, then apply again"
        continue
      fi
      warn "$d predates stable UUIDs; recreating it once"
      virsh undefine "$d" >/dev/null
    fi

    virsh define "$MANIFEST/domains/$n.xml" >/dev/null
    log "domain $d defined"
  done
}

wait_ready() {
  local n deadline
  for n in "$@"; do
    log "waiting for $n — first boot installs packages, so give it a few minutes"
    deadline=$(( $(date +%s) + 1200 ))
    until sshx "$n" true 2>/dev/null; do
      if [ "$(date +%s)" -gt "$deadline" ]; then
        die "$n never answered. Watch it boot with: lfcs-lab console $n"
      fi
      sleep 5
    done
    # Let cloud-init finish its package installs before calling the node ready.
    # This needs root on EL9: an unprivileged user cannot read
    # /run/cloud-init/cloud.cfg, and `--wait` spins on that error forever
    # rather than exiting, which hung install for as long as you let it — with
    # ssh answering the whole time. The || true only ever caught a bad exit
    # code, never a command that does not return, so bound it too.
    sshx_t 600 "$n" "sudo cloud-init status --wait" >/dev/null 2>&1 || true
    log "$n ready"
  done
}

# --------------------------------------------------------------------------

cmd_install() {
  preflight
  keep_sudo_alive
  ensure_key
  sudo mkdir -p "$STATE"/{base,disks,seed,snapshots}
  stop_running
  # install is the from-scratch command: every guest disk is recreated, so
  # anything living on one is gone. Say so rather than let it be a surprise.
  if [ -n "$(sudo sh -c 'ls -A "$1"/disks 2>/dev/null' _ "$STATE")" ]; then
    warn "recreating all guest disks — everything inside the current guests is discarded"
    warn "(snapshots under $STATE/snapshots are kept; 'lfcs-lab load <name>' restores one)"
  fi
  fetch_images
  local n
  for n in "${NODES[@]}"; do
    make_disks "$n"
    make_seed "$n"
  done
  define_nets
  define_domains
  for n in "${NODES[@]}"; do
    virsh start "$(dom "$n")" >/dev/null
  done
  wait_ready "${NODES[@]}"
  log "taking the 'clean' snapshot every reset returns to"
  cmd_down "${NODES[@]}"
  cmd_save clean
  cmd_up
  cmd_status
  cat >&2 <<EOF

The lab is up. Useful next moves:

  lfcs-lab ssh node-1          shell on the Ubuntu node
  lfcs-lab ssh node-2          shell on the Rocky node (dnf, firewalld, SELinux)
  lfcs-lab console node-1      serial console, works when ssh does not
  lfcs-lab break fstab node-1  poison /etc/fstab and reboot into the emergency shell
  lfcs-lab reset               undo everything, back to 'clean'

node-3 is defined but stopped. Start it when you need a second peer:
  lfcs-lab up node-3
EOF
}

cmd_apply() {
  preflight
  define_nets
  define_domains
  log "definitions updated. Changes to memory, CPU or NICs apply at next boot."
}

cmd_up() {
  preflight
  local sel n
  mapfile -t sel < <(pick "$@")
  for n in "${sel[@]}"; do
    if [ "$(state_of "$n")" = "running" ]; then
      log "$n already running"
    else
      virsh start "$(dom "$n")" >/dev/null
      log "$n starting"
    fi
  done
}

cmd_down() {
  local sel n i
  mapfile -t sel < <(pick "$@")
  for n in "${sel[@]}"; do
    virsh shutdown "$(dom "$n")" >/dev/null 2>&1 || true
  done
  for n in "${sel[@]}"; do
    for ((i = 0; i < 60; i++)); do
      if [ "$(state_of "$n")" = "shut off" ]; then break; fi
      sleep 2
    done
    if [ "$(state_of "$n")" != "shut off" ]; then
      warn "$n ignored the ACPI shutdown, pulling the plug"
      virsh destroy "$(dom "$n")" >/dev/null 2>&1 || true
    fi
    log "$n down"
  done
}

cmd_status() {
  printf '%-9s %-8s %-15s %-10s %s\n' NODE DISTRO IP STATE SSH
  local n st reach
  for n in "${NODES[@]}"; do
    st="$(state_of "$n")"
    if [ -z "$st" ]; then st="undefined"; fi
    reach="-"
    if [ "$st" = "running" ]; then
      if sshx "$n" true 2>/dev/null; then reach="ok"; else reach="booting"; fi
    fi
    printf '%-9s %-8s %-15s %-10s %s\n' \
      "$n" "${NODE_DISTRO[$n]}" "${NODE_IP[$n]}" "$st" "$reach"
  done
}

cmd_ssh() {
  local n="${1:-node-1}"; shift || true
  if ! known "$n"; then die "unknown node: $n"; fi
  sshx "$n" "$@"
}

cmd_console() {
  local n="${1:-node-1}"
  if ! known "$n"; then die "unknown node: $n"; fi
  warn "escape sequence is Ctrl+] — press Enter first if the screen looks blank"
  warn "console login: $LABUSER or root, password set in lab.nix"
  virsh console "$(dom "$n")"
}

cmd_save() {
  local name="${1:-}"
  if [ -z "$name" ]; then die "usage: lfcs-lab save <name>"; fi
  if [ "$name" != "clean" ]; then
    log "shutting the lab down so the copy is crash-consistent"
    cmd_down "${NODES[@]}"
  fi
  sudo bash -c 'mkdir -p "$2" && cp --reflink=auto -f "$1"/disks/*.qcow2 "$2"/' \
    _ "$STATE" "$STATE/snapshots/$name"
  log "saved snapshot '$name'"
}

cmd_load() {
  local name="${1:-clean}" n
  if ! sudo test -d "$STATE/snapshots/$name"; then
    die "no snapshot named '$name'. Existing: $(sudo ls "$STATE/snapshots" 2>/dev/null | tr '\n' ' ')"
  fi
  for n in "${NODES[@]}"; do
    virsh destroy "$(dom "$n")" >/dev/null 2>&1 || true
  done
  sudo bash -c 'cp --reflink=auto -f "$1"/*.qcow2 "$2"/disks/' \
    _ "$STATE/snapshots/$name" "$STATE"
  log "restored '$name'"
}

cmd_reset() {
  cmd_load clean
  cmd_up
  log "back to a pristine lab"
}

cmd_destroy() {
  local n
  warn "this deletes every guest disk and snapshot under $STATE"
  read -r -p "type the word yes to continue: " answer
  if [ "$answer" != "yes" ]; then die "aborted"; fi
  for n in "${NODES[@]}"; do
    virsh destroy "$(dom "$n")" >/dev/null 2>&1 || true
    virsh undefine "$(dom "$n")" >/dev/null 2>&1 || true
  done
  for n in "${NETS[@]}"; do
    virsh net-destroy "$n" >/dev/null 2>&1 || true
    virsh net-undefine "$n" >/dev/null 2>&1 || true
  done
  sudo rm -rf "$STATE"
  log "lab removed. The base images went with it; install will re-download."
}

# --------------------------------------------------------------------------
# Breakage drills. Each one only creates the symptom — never the fix.
# `lfcs-lab reset` is always the way out if you get properly stuck.
# --------------------------------------------------------------------------

break_fstab() {
  local n="$1"
  sshx "$n" "sudo bash -s" <<'EOS'
set -e
mkdir -p /srv/broken
printf 'UUID=deadbeef-0000-0000-0000-000000000000 /srv/broken ext4 defaults 0 2\n' >> /etc/fstab
EOS
  log "poisoned /etc/fstab on $n, rebooting"
  virsh reboot "$(dom "$n")" >/dev/null
  warn "$n will stop in an emergency shell. ssh will NOT work."
  warn "get in with: lfcs-lab console $n"
}

break_service() {
  local n="$1" svc
  if [ "${NODE_DISTRO[$n]}" = "rocky" ]; then svc="chronyd"; else svc="chrony"; fi
  sshx "$n" "sudo bash -s" <<EOS
set -e
mkdir -p /etc/systemd/system/$svc.service.d
printf '[Service]\nExecStart=\nExecStart=/usr/bin/false\n' > /etc/systemd/system/$svc.service.d/override.conf
systemctl daemon-reload
systemctl restart $svc || true
EOS
  warn "$svc on $n is now failing to start. Find out why from the journal, then fix it."
}

break_dns() {
  local n="$1"
  sshx "$n" "sudo bash -s" <<'EOS'
set -e
rm -f /etc/resolv.conf
printf 'nameserver 203.0.113.53\nsearch invalid.\n' > /etc/resolv.conf
chattr +i /etc/resolv.conf 2>/dev/null || true
EOS
  warn "name resolution on $n is broken. Numeric ssh still works. Note the immutable bit."
}

break_sudoers() {
  local n="$1"
  sshx "$n" "sudo bash -s" <<'EOS'
set -e
printf 'lab ALL=(ALL NOPASSWD:ALL\n' > /etc/sudoers.d/99-lab-broken
chmod 0440 /etc/sudoers.d/99-lab-broken
EOS
  warn "sudo on $n is now broken for every user — an unclosed paren in /etc/sudoers.d."
  warn "recover from the console as root: lfcs-lab console $n, then visudo -c"
}

cmd_break() {
  local scenario="${1:-}" n="${2:-node-1}"
  if ! known "$n"; then die "unknown node: $n"; fi
  case "$scenario" in
    fstab)   break_fstab   "$n" ;;
    service) break_service "$n" ;;
    dns)     break_dns     "$n" ;;
    sudoers) break_sudoers "$n" ;;
    *)
      cat >&2 <<'EOF'
usage: lfcs-lab break <scenario> [node]

  fstab     bad UUID in /etc/fstab, then reboot -> emergency shell
            (week 1 drill: recover from the console, twice)
  service   chrony fails to start via a drop-in override
            (read the journal, find the override, remove it)
  dns       resolv.conf clobbered and made immutable
            (lsattr is the thing most people forget)
  sudoers   syntax error in /etc/sudoers.d -> sudo refuses everything
            (root console + visudo -c)
EOF
      exit 1
      ;;
  esac
}

usage() {
  cat <<EOF
lfcs-lab — a disposable Linux practice lab defined in lab.nix

  install              download images, define everything, first boot, snapshot
  apply                regenerate libvirt XML from lab.nix without touching disks
  up [node...]         start (default: nodes marked autostart)
  down [node...]       graceful shutdown, force after two minutes
  status               what is defined, running and reachable
  ssh <node> [cmd]     shell or one-shot command
  console <node>       serial console; works when the box will not boot
  reset                restore the 'clean' snapshot and start again
  save <name>          snapshot all disks under a name
  load <name>          restore a named snapshot
  break <scenario>     create a failure to practise recovering from
  destroy              delete every disk, snapshot and definition

nodes:   ${NODES[*]}
network: $SUBNET.0/24 NAT for ssh, plus an isolated segment for bonding
state:   $STATE
EOF
}

main() {
  local cmd="${1:-status}"
  shift || true
  case "$cmd" in
    install) cmd_install "$@" ;;
    apply)   cmd_apply   "$@" ;;
    up)      cmd_up      "$@" ;;
    down)    cmd_down    "$@" ;;
    status)  cmd_status  "$@" ;;
    ssh)     cmd_ssh     "$@" ;;
    console) cmd_console "$@" ;;
    reset)   cmd_reset   "$@" ;;
    save)    cmd_save    "$@" ;;
    load)    cmd_load    "$@" ;;
    break)   cmd_break   "$@" ;;
    destroy) cmd_destroy "$@" ;;
    -h|--help|help) usage ;;
    *) usage; exit 1 ;;
  esac
}

main "$@"
